[package]
name = "day10ui"
version = "0.1.0"
edition = "2021"

[dependencies]
day10 = { path = "../rs" }
ui = { path = "../../common/rs/ui", features = ["wasm-bindgen"]}

[build-dependencies]
aoc = { path = "../../common/rs/aoc"}

[dependencies.yew]
version = "0.21"
features = ["csr"]